apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    version: v0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        version: v0
    spec:
      containers:
      - name: registry
        image: registry:2.5.0-rc.1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE
          value: "azure"
        - name: REGISTRY_STORAGE_AZURE_ACCOUNTNAME
          valueFrom:
            secretKeyRef:
              name: azure-storage-key
              key: storageaccount
        - name: REGISTRY_STORAGE_AZURE_ACCOUNTKEY
          valueFrom:
            secretKeyRef:
              name: azure-storage-key
              key: storagekey
        - name: REGISTRY_STORAGE_AZURE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: azure-storage-key
              key: storagecontainer
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP

